name: CICD for Java application using maven

on: 
  push:
    branches: ['main']

jobs:
  name: Building Java application
  build: 
    runs-on: ubuntu-latest
    steps:
# Setup java and getting code----------------------------------------------------
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

# Maven Build Starts--------------------------------------------------------------
      # - name: Maven Validation
      #   run: mvn validate
      # - name: Maven Compile
      #   run: mvn clean compile
      # - name: Maven test
      #   run: mvn test

#SonarQube------------------------------------------------------------------------
      # - name: Sonarqube code analysis
      #   env:
      #     token: ${{secrets.SONARQUBE_TOKEN}}
      #   run: |
      #     mvn sonar:sonar \
      #       -Dsonar.projectKey=trainapp \
      #       -Dsonar.host.url=${{secrets.SONARQUBE_URL}} \
      #       -Dsonar.login=${token}


      - name: Maven package (.war file creation)
        run: mvn clean package

      - name: Store Artifact in Github storage
        uses: actions/upload-artifact@v4
        with:
          name: webapps
          path: target/*.war
  