name: CICD for Java application using maven
on: 
  push:
    branches: ['main']

jobs:
  build:
    name: Building an Java application
    runs-on: ubuntu-latest
    steps:
# Setup java and getting code----------------------------------------------------
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

# Maven Build Starts--------------------------------------------------------------
      # - name: Maven Validation
      #   run: mvn validate
      - name: Maven Compile
        run: mvn clean compile
      # - name: Maven test
      #   run: mvn test

#SonarQube------------------------------------------------------------------------
      # - name: Sonarqube code analysis
      #   env:
      #     token: ${{secrets.SONARQUBE_TOKEN}}
      #   run: |
      #     mvn sonar:sonar \
      #       -Dsonar.projectKey=trainapp \
      #       -Dsonar.host.url=${{secrets.SONARQUBE_URL}} \
      #       -Dsonar.login=${token}

      - name: Install Snyk CLI
        run: |
          curl -s https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Snyk Security Scan
        # run: snyk test --severity-threshold=high || true
        run: synk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload results to Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Maven package (.war file creation)
        run: mvn clean package

      - name: Store Artifact in Github storage
        uses: actions/upload-artifact@v4
        with:
          name: webapps
          path: target/*.war
# Dev Env
  development:
    name: Deploying Application on Dev Environment
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapps
      - name: Deploy in Server
        run: |
          User="${{secrets.TOMCAT_USER}}"
          Pass="${{secrets.TOMCAT_PASSWORD}}"
          Server="${{secrets.DEV_SERVER}}"
          App_Env="development"

          curl -v -u "$User:$Pass" \
          --upload-file *.war \
          "http://$Server:8080/manager/text/deploy?path=/$App_Env&update=true"

# Test Env
  test:
    name: Deploying Application on Test Environment
    needs: development
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapps
      - name: Deploy on Test Server
        run: |
          User="${{secrets.TOMCAT_USER}}"
          Pass="${{secrets.TOMCAT_PASSWORD}}"
          Server="${{secrets.TEST}}"
          App_Env="test"

          curl -v -u "$User:$Pass" \
          --upload-file *.war \
          "http://$Server:8080/manager/text/deploy?path=/$App_Env&update=true"

# Pre_Production Env
  preprod:
    name: Deploying Application on Pre_Production Environment
    needs: test
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapps
      - name: Deploy on Pre_Production Server
        run: |
          User="${{secrets.TOMCAT_USER}}"
          Pass="${{secrets.TOMCAT_PASSWORD}}"
          Server="${{secrets.PRE_PROD}}"
          App_Env="kp"

          curl -v -u "$User:$Pass" \
          --upload-file *.war \
          "http://$Server:8080/manager/text/deploy?path=/$App_Env&update=true"

# Production Env
  production:
    name: Deploying Application on Production Environment
    needs: preprod
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapps
      - name: Deploy on Production Server
        run: |
          User="${{secrets.TOMCAT_USER}}"
          Pass="${{secrets.TOMCAT_PASSWORD}}"
          Server="${{secrets.PROD}}"
          App_Env="prod"

          curl -v -u "$User:$Pass" \
          --upload-file *.war \
          "http://$Server:8080/manager/text/deploy?path=/$App_Env&update=true"
  